config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'session/login' => 'session#login'
    post 'session/create' => 'session#create'
    get 'session/logout' => 'session#logout'
    resources :users
    resources :posts
    root 'posts#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :ingr
  has_rich_text :way
  validates :name, :author, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
  before_action :require_login, :set_locale

  private
  def require_login
    redirect_to session_login_url unless signed_in?
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale || session[:locale]
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
      parsed_locale.to_sym :
      nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy]
  before_action :require_login, only: %i[edit update destroy ]
  skip_before_action :verify_authenticity_token, only: :update

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :author, :time, :ingr, :way, :picname)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:login, :create]
  def login; end

  def create
    user = User.find_by username: params[:username]

    if user&.authenticate(params[:password])
      p 'LOGIN'
      sign_in user
      redirect_to posts_url
    else
      p 'REDIRECT'
      redirect_to session_login_url
    end
  end

  def logout
    sign_out
    redirect_to session_login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[new create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 10.days }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipenew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        body {
            margin-left: 200px;
            margin-right: 200px;
        }
        div.all {
            width: 1200px;
            height: max-content;
        }
        div.item_ {
            position: relative;
            margin-top: 50px;
            margin-bottom: 20px;
            height: 300px;
            width: 300px;
            transition: transform .8s;
        }
        div.item_:hover {
            transform: scale(1.1);
            -webkit-filter: brightness(70%);
            transition: 0.5s;
        }
        .img-circular{
            display: flex;
            -webkit-border-radius: 40px;
        }
        span.name_ {
            text-align: center;
            font-size: xx-large;
            color: #ffffff;
        }
        div.look {
            width: 100%;
            height: 350px;
            overflow: hidden;
        }
        .img-look {
            width: 1400px;
            height: 400px;
            object-fit: cover;
            filter: blur(10px);
            -webkit-filter: blur(10px) brightness(0.5);
            margin-top: -10px;
            margin-left: -10px;

        }
        .main-text {
            color: #950da4;
        }
        .main-text:hover {
            color: #6826ec;
            text-decoration: none;
            transition: 0.5s;
        }
        .container {
            position: relative;
            text-align: center;

        }
        .centered {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        .bottom {
            position: absolute;
            top: 60%;
            left: 50%;
        }
        .del {
            width: 40px;
            height: 40px;
            margin-top: 30px;
            margin-left: 50px;
        }
        .bordered{
            background-color: #fcfafb;
            border: 3px solid #c8b6d3;
            -webkit-border-radius: 20px;
            margin-top: 20px;
        }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t'posts.show.name' %>
    <%= form.text_field :name, class:"bordered"%>
    <br/>
    <%= form.hidden_field :author, value: current_user.username %>
    <%= form.label t'posts.show.time' %>
    <%= form.text_field :time , class:"bordered"%>
    <br/><br/>
    <%= form.label t'posts.show.ingr' %>
    <%= form.rich_text_area :ingr %>
    <br/>
    <%= form.label t 'posts.show.way' %>
    <%= form.rich_text_area :way %>
    <br/>
    <%= form.label t 'posts.show.pic' %>
    <%= form.text_field :picname , class:"bordered"%>
  </div>
    <br/><br/>
  <div class="actions">
    <%= form.submit 'Done', class:"btn btn-outline-success"%>
  </div>
    <br/>
<% end %>

app/views/posts/edit.html.erb
<h1><%= t '.ed' %></h1>

<%= render 'form', post: @post %>

<div class="container">
  <div class="row">
    <h3><%= link_to 'Show', @post, class:"main-text" %></h3>
    <h3 style="margin-left: 40px;"><%= link_to 'Back', posts_path, class:"main-text" %></h3>
  </div>
</div>
<br/>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-2">
      <h1><%= t '.all_recipes' %></h1>
      <h2 style="margin-left: -90px"><%= link_to 'EN', root_path(locale: :en), class:"main-text"%></h2>
      <h2 style="margin-left: -90px"><%= link_to 'RU', root_path(locale: :ru), class:"main-text" %></h2>
    </div>
    <div class="col-6"></div>
    <% if signed_in? %>
    <div class="col-4">
      <h4 class="text-secondary" style="text-align: right"><%= t('.in_acc') + current_user.username %></h4>
      <h2 style="text-align: right"><%= link_to t('.create_recipe'), new_post_url, class:"main-text" %></h2>
      <h2 style="text-align: right"><%= link_to t('.link_logout'), session_logout_url, class:"main-text"%></h2>
    </div>
    <% else %>
      <h2 style="text-align: right"><%= link_to t('.link_login'), session_login_url, class:"main-text" %></h2>
    <% end %>
  </div>
</div>

<br/>

<div class="all container", id="all_location">
  <div class="row justify-content-around">
    <% @posts.each do |recipe| %>
      <% recipe.picname = 'none.jpg' if recipe.picname ==""%>
      <div class="col-4">
        <div class="item_">
          <%=link_to image_tag("pics/#{recipe.picname}", width: "300px", height: "300px",
                               class: "img-circular", title: "#{recipe.name}"),
                     "/posts/#{recipe.id}" %>
          <h5><%= recipe.name %></h5>
        </div>
        <br/>
      </div>
    <% end %>
  </div>
</div>
<br/><br/>
<h2 style="text-align: right"><%= link_to t('session.login.create_user'), new_user_url, class:"main-text"%></h2>
<br/><br/>

app/views/posts/new.html.erb
<h1><%= t '.new_recipe' %></h1>

<%= render 'form', post: @post %>

<h3><%= link_to 'Back', posts_path, class:"main-text" %></h3>
<br/><br/>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="look">
    <% if @post.picname == "" %>
      <%= image_tag("pics/none.jpg", class: "img-look") %>
    <% else %>
      <%= image_tag("pics/#{@post.picname}", class: "img-look") %>
    <% end %>
  </div>
  <h1 class="centered" style="color: white"><%= @post.name %></h1>
  <h2 class="bottom" style="color: white"><%= @post.time %></h2>
</div>
<br/><br/>
<h3>
  <strong><%= t '.au' %>:</strong>
  <%= @post.author %>
</h3>
<h2><%= t '.ingr' %>:</h2>
<h3><%= @post.ingr %></h3>
<br/><br/>
<h3><%= @post.way %></h3>
<br/><br/>
<div class="container">
  <div class="row">
    <% if signed_in? && current_user.username == @post.author %>
    <h2><%= link_to t('.edit_recipe'), edit_post_path(@post), class:"main-text"%></h2>
    <h2 style="margin-left: 40px"><%= link_to t('.button_del'), @post, method: :delete,
                      data: {confirm: 'Are you sure?'}, class:"text-danger" %></h2>
    <% end %>
    <h2 style="margin-left: auto; margin-right: 0px"><%= link_to t('both.to_recipes'),
                                                                 posts_url, class:"main-text" %></h2>
  </div>
</div>
<br/>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/login.html.erb
<style>
    body {
        background: url(<%= image_url 'pics/none.jpg' %>) no-repeat center;
        -webkit-background-size: cover;
    }
    div.main {
        margin-left: -70px;
        width: 1200px;
        height: 700px;
        backdrop-filter: blur(150px);
    }
    .m {
        margin-left: 100px;
        margin-top: 5px;
    }
    .inp {
        border: 4px solid #b9b9e3;
        -webkit-border-radius: 20px;
    }
    .t {
        color: white;
    }
</style>

<div class="main">
  <h1 class="m t"><%= t '.hello' %></h1><br/>

  <h2 class="m t"><%= t '.if_not_reg' %></h2>
  <h3 class="m t"><%= link_to t('.create_user'), new_user_path, class: 'btn btn-outline-light' %></h3><br/>

  <%= form_with url: session_create_url, method: :post, local: true do |form| %>
    <h3 class="m t"><%= form.label  t '.name'%></h3>
    <h3 class="m"><%= form.text_field :username, class: "inp" %><br/><br/></h3>
    <h3 class="m t"><%= form.label t '.pass' %></h3>
    <h3 class="m"><%= form.password_field :password, class: "inp" %></h3><br/><br/>
    <%= form.submit t('.button_login'), class: 'btn btn-success m'%><br/><br/>
  <% end %>

  <button type="button" class="btn btn-light m">
    <%= link_to t('.button_logout'), :controller => :session, :action => :logout%>
  </button>
  <br/><br/><br/><br/>
  <h3 class="m"><%=link_to  t('both.to_recipes'), posts_url, class:"t" %></h3>
</div>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/users/_form.html.erb
<style>
    .inp {
        border: 4px solid #b9b9e3;
        -webkit-border-radius: 20px;
    }
</style>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= t 'session.login.name' %></h3>
    <h3><%= form.text_field :username, class: "inp" %></h3>
  </div><br/>

  <div class="field">
    <h3><%= t 'session.login.pass'%></h3>
    <h3><%= form.password_field :password, class: "inp" %></h3>
  </div><br/>

  <div class="field">
    <h3><%= t 'session.login.pass' %></h3>
    <h3><%= form.password_field :password_confirmation, class: "inp" %></h3>
  </div><br/>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t '.users_' %></h1>
<br/><br/>

<table>
  <thead>
  <tr>
    <th><h2><%= t 'session.login.name' %></h2></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><h4><%= user.username %></h4></td>
      <td><%= link_to t('.link_show'), user %></td>
      <% if current_user == user %>
        <td><%= link_to t('.link_update'), edit_user_path(user) , style:"margin-left: 20px;"%></td>
        <td><%= link_to t('.link_destroy'), user, method: :delete,
                        data: { confirm: 'Are you sure?' } , style:"margin-left: 20px;"%></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br/><br/><br/>

<h2><%= link_to t('.log_page'), session_login_url, class: 'text-danger'%></h2>
<br/>
<h2><%= link_to t('both.to_recipes'), posts_url, class: 'text-danger'%></h2>

app/views/users/new.html.erb
<h1><%= t 'users.new' %></h1>

<%= render 'form', user: @user %>
<br/>

<h2><%= link_to t('users.index.users_'), users_url, class: 'main-text'%></h2>
<br/>
<h2><%= link_to t('both.to_recipes'), posts_url, class: 'main-text'%></h2>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>

<% if current_user == @user %>
  <%= link_to t('users.index.link_update'), edit_user_path(@user) %>
<% end %>
|
<%= link_to t('users.index.users_'), users_path %>